[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production", TZ = "America/Los_Angeles" }

[dev]
  command = "npm run start"
  publish = "dist"
  port = 3000
  targetPort = 8080
  NODE_ENV = "development"

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
